### ISSUE TITLE
Roadmap and Timeline - General questions!

### ISSUE THREAD

**Issue by zulfgani** [yumecommerce/pagex#2]
Hi there.

Is there a public roadmap fort this plugin?

I'm interested in taking a much closer look at its usage and how to best support it but would like to know some specific plans for the medium to long term of the development.

Will the plugin be submitted to the WordPress org repository?

Will you be adding options for themers to selectively use the default theme's header/footer functions with the option to switching to those created by the plugin?

Is there a public API for developer to extend the plugin either via a theme or an addon  plugin?

Is this likely to move into the Gutenberg territory or will it remain neutral and therefore be compatible with the ClassicPress CMS?

Finally, could you set up a "Develop" branch so PRs can be pushed to that before merging into the Master branch. If so, could you provide the unminified versions of the styleheets and js to facilitate ease of development please?

**Comment by komarovartem** [comment]
Hi,

This plugin mainly exists to provide an efficient and fast way for our company to develop themes and small websites that can have long support and compatibility without relying too much on everyday support. 

So this plugin will not be submitted to WordPress since there are already plenty of similar plugins. And I do not think it is a good idea to make public API and create additional branches for this plugin at this stage of development.
